### ISSUE TITLE
What is the best way to fork a SignalProducer?

### ISSUE THREAD

**Issue by guidomb** [ReactiveCocoa/ReactiveCocoa#2243]
I was thinking of adding this function to my projects (and submitting a PR to ReactiveCocoa) to be able to fork `SignalProducer`. That before doing so I want to know if there is a better way of doing this.

This is an example of forking a `SignalProducer`:

```swift
let producer: SignalProducer<Int, NSError> = ...
let errorWrapper: NSError -> MyCustomErrorType = ...

producer
    |> mapError { errorWrapper($0) }
    |> fork { $0
        |> take(1)
        |> map { $0 * $0 }
        |> catch { _ in SignalProducer<Int, MyCustomErrorType>(value: 0) }
        |> on { println("The first value is \($0)") }
    }
    |> map { $0 * 10 }
    |> reduce(initial: 0) { (sum, value) in  sum + value }
    |> start(next: { result in println("The result is \(result)") })
```

The forked `SignalProducer` would be started when the original producer is started and will receive the same events. `fork` could be implemented as 

```swift
func fork<T, E: ErrorType>(forkedExecution: SignalProducer<T, E> -> ()) -> SignalProducer<T,E> -> SignalProducer<T,E> {
    let (signal, sink) = Signal<T, E>.pipe()
    let forkedProducer = SignalProducer<T, E> { (observer, _) in signal.observe(observer) }
    
    return { producer in
        forkedExecution(forkedProducer)
        
        var started = false
        return producer |> on(event: { event in
            if !started {
                started = true
                forkedProducer.start()
            }
            sink.put(event)
        })
    }
}
```

What do you think?

**Comment by neilpa** [comment]
What scenario would you use this in? I'm having a hard time figuring out why you would need this.

**Comment by neilpa** [comment]
> would be started when the original producer is started and will receive the same events

This isn't guaranteed since you're starting multiple producers. Seems like what you really want is to start the underlying producer via `startWithSignal` and share the signal with the different observers.

**Comment by guidomb** [comment]
OK let me explain a little bit of how I came with this idea.

I am currently working on an app that needs to connect to another device using Bluetooth Low Energy. In this app there is a screen to discover all the devices that are advertising their services. When the user taps on the "add device" button a spinner appears and when the first device is discovered a new screen appears showing the list of discovered devices. The discovery process is async and the devices are discovered one at a time.

I am using a  [library](https://github.com/Wolox/WLXBluetoothDevice) that wraps CoreBluetooth that makes the discovery/connection process easier and uses ReactiveCocoa.

The following piece of code shows how the action that is bouded to the "add device" button is created in the screen's view model:

```swift
self.addDeviceAction = Action(enabledIf: canAddDevice) { [unowned self](_) in
  self._state.put(.Discovering)
  let devicePickerViewModel = DevicePickerViewModel(devices: self.addDevice.values)
  
  return deviceDiscoverer
      |> mapError { Errors.DiscoveryError($0) }
      |> fork { $0
        // When the first device has been discovered we need
        // to present the device picker view
        |> take(1)
        |> map { _ in State.ShowDiscoveredDevices(viewModel: devicePickerViewModel) }
        |> catch { _ in SignalProducer<State, NoError>(value: .ReadyToDiscover) }
        |> on { self.changeState($0) }
      }
      |> concat(SignalProducer { (observer, _) in
        // If the discovery process has stopped we need to check
        // if a device has been discovered. If not we send
        // an error
        if devicePickerViewModel.discoveredDevicesCount == 0 {
          self.changeState(.ReadyToDiscover)
          sendError(observer, Errors.DevicesNotFound)
        } else {
          sendCompleted(observer)
        }  
      })
}
```

I have omitted the rest of code from the view model but I think you can get the point. `deviceDiscoverer` is a signal producer what will send a value every time a new device is discovered by the CoreBluetooth framework.

A couple of things to note here is that the actual signal producer that is returned to the action only checks if at least one device was discovered and sends a value every time a new device is discovered. It also maps the discovery error coming from CoreBluetooth. The forked signal producer only cares about the first discovered device. It maps the value to an internal state value and also catches the error and finally executes a side effect depending of the result of signal producer to change the `state` property of the view model. (This property is used by the controller to adjust the look of the view).

Probably there are other ways to implement this, as a matter of fact this is not how I ended up implementing it (I did all the side effect login inside the on closure on the original signal producer) but I think that this reads better because by forking the signal producer I can make use of all the transformation functions.

Another important think is that this code does not starts the signal producer. The one that starts it is the action when it gets applied.

I think that the fork concepts goes really well with signals and signal producers because for me they are pretty similar of how you do unix programming by pipping command. And the fork command could be think as the `tree` command in unix.

Did I make my self clear? What do you think? @neilpa

**Comment by neilpa** [comment]
From past experience, I'll say that the CoreBluetooth delegate pattern is difficult to map well to ReactiveCocoa. I spent time a few months ago experimenting with different approaches but never landed on something I liked. Check out the history of https://github.com/neilpa/circulate/tree/swift/Source if you're really curious (be warned, there were lots of experimental and half-baked iterations).

That said, I think your scenario could be solved more simply with [`scan`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/e6ad571e8c719f86cde82590b022586565d806fe/ReactiveCocoa/Swift/Signal.swift#L572-L577). That'll let you collect all the devices as there discovered with the ability to have the special logic for the first one without have to "fork".

**Comment by guidomb** [comment]
@neilpa I dont think `scan` provides a way to solve this more simply. Because if  I have to collect the values (lets say in an array) then If I still want the behavior of sending a value of each device as they are discovered I would need to create another signal and send values to that signal manually. Shouldn't I?

In my personal opinion an operation like `fork` lets you use all the combinators from `SignalProducer` and makes the code really clean. Again, if you think of signasl or signal producers as pipes in the same way as unix pipes an operation like `fork` makes a lot of sense. What is that you don't like about it?

Regarding CoreBluetooth I also implemented a lib to wrap it. I still using RAC 2.0 and the library has a block-based API and a RAC based one. Check it out if you want, it is called [WLXBluetoothDevice](http://github.com/Wolox/WLXBluetoothDevice). I am quite happy with the API but the implementation is really complex and could be improved. CoreBluetooth is dificult to wrap.

**Comment by neilpa** [comment]
The main problem with `fork` is that it breaks the contract for a `SignalProducer`. A producer represents a unit of deferred work that must be explicitly started by the consumer. That's not the case here as the `fork`ed producer is implicitly started whenever the parent producer is.

I mentioned `startWithSignal` earlier, but maybe you missed it. This method gives you access to the underlying signal from a producer that you can the share with different consumers. Essentially what you're trying to do here.

**Comment by neilpa** [comment]
> Again, if you think of signasl or signal producers as pipes in the same way as unix pipes an operation 

This is true for a "hot" `Signal` which is essentially push driven but not a "cold" `SignalProducer`.

**Comment by neilpa** [comment]
Using your original example

```swift
let producer: SignalProducer<Int, NSError> = ...
let errorWrapper: NSError -> MyCustomErrorType = ...

producer
    |> mapError { errorWrapper($0) }
    |> startWithSignal { signal in
        signal
            |> take(1)
            |> map { $0 * $0 }
            |> catch { _ in SignalProducer<Int, MyCustomErrorType>(value: 0) }
            |> observe(next: { println("The first value is \($0)") })

        signal
            |> map { $0 * 10 }
            |> reduce(initial: 0) { (sum, value) in  sum + value }
            |> observe(next: { result in println("The result is \(result)") })
    }
```

Note that this is safe because the signal passed to the closure is guaranteed to not start sending values until after the closure executes.

**Comment by guidomb** [comment]
About `startWithSignal` I think you are right. It is the cleaner solution. The only problem with it is that you are starting the signal producer. Which is not something you want to do for example inside the closure of an `Action`. Which happens to be the case where I was trying to use the `fork` operator.

I think that a good implementation of `fork` could use signals instead of signal producers and will avoid the problem of breaking its contract. Such implementation could be something like:

```swift
func fork<T, E: ErrorType>(forkedExecution: Signal<T, E> -> ()) -> SignalProducer<T,E> -> SignalProducer<T,E> {
    let (signal, sink) = Signal<T, E>.pipe()

    return { producer in
        forkedExecution(signal)
        return producer |> on(event: {  sink.put($0) })
    }
}
```

and it can be used in the same way as before

```swift
let producer: SignalProducer<Int, NSError> = ...
let errorWrapper: NSError -> MyCustomErrorType = ...

producer
    |> mapError { errorWrapper($0) }
    |> fork { $0
        |> take(1)
        |> map { $0 * $0 }
        |> catch { _ in SignalProducer<Int, MyCustomErrorType>(value: 0) }
        |> observe(next: { println("The first value is \($0)") })
    }
    |> map { $0 * 10 }
    |> reduce(initial: 0) { (sum, value) in  sum + value }
    |> observe(next: { result in println("The result is \(result)") })
```

@neilpa Whether something like this endups in a ReactiveCocoa or not thanks for taking the time to discuss it.
